### PR TITLE
Is there any additional work from this branch that Doug would like to merge into the Master?

### PR DESCRIPTION
**Pull request by boshek**

### CODE REVIEW

**Comment by boshek** [comment]
Upon further reflection, it is probably hard for this to be merged and it might not be sensible. So much has changed already. Anything of left value in this branch is probably more the question that I am thinking of here?

**Comment by DougCollinge** [comment]
I'll have to go over all these updates tomorrow. As I commented, I think it may all just go in the bucket. I think sm_plot is quite useful, so cherrypick that one if you haven't already.

**Comment by DougCollinge** [comment]
OK, no I don't think there is anything worth saving. The sm_plot probably is but I imagine that you have already merged that into master. So hit it, I say. I mean, just drop it. I'll probably delete the branch because I don't think it needs to exist anymore. Personally, I think this algorithm is not optimal and I would like to work on a better one but I'll start that work from whatever the master is at the time.

**Review by DougCollinge — COMMENTED** [review]
I agree, see comment. Basically, merge not required so long as sm_plot has been included in the master.

**Comment by boshek** [comment]
One option to re-write the algorithm in C++ and the access that routine via R's Rcpp package. I don't have a good sense of how hard/easy that would be.

**Comment by DougCollinge** [comment]
I don't think there is a good reason to do that. Anyway, we should probably
have a go at making it into better R first.

**Comment by boshek** [comment]
I guess just a small speed gain using C++ no?

**Comment by DougCollinge** [comment]
No particular need for speed on this application, right? Quite small data
by modem standards.

**Comment by DougCollinge** [comment]
On Jun 12, 2017 10:57 AM, "Sam Albers" <notifications@github.com> wrote:

------------------------------
You can view, comment on, or merge this pull request online at:

  https://github.com/boshek/limnotools/pull/18
Commit Summary

   - Revised spl.R
   - Merge branch 'master' into dougwork
   - Made r2b and s_m_p follow published algorithm
   - Merge branch 'master' into dougwork
   - Added sm_plot.R
   - Update docs
   - Parametrized sm_plot.
   - Added segmented class and tests.
   - r2b revised to also return slope and intercept.
   - I think I am abandoning this branch
   - Adapt to list output of r2b

File Changes

   - *M* NAMESPACE
   <https://github.com/boshek/limnotools/pull/18/files#diff-0> (1)
   - *M* R/r2b.R <https://github.com/boshek/limnotools/pull/18/files#diff-1>
   (41)
   - *M* R/s_mN.R
   <https://github.com/boshek/limnotools/pull/18/files#diff-2> (6)
   - *M* R/s_m_p.R
   <https://github.com/boshek/limnotools/pull/18/files#diff-3> (315)
   - *A* R/segmented.R
   <https://github.com/boshek/limnotools/pull/18/files#diff-4> (82)
   - *A* R/sm_plot.R
   <https://github.com/boshek/limnotools/pull/18/files#diff-5> (31)
   - *M* R/split_interval.R
   <https://github.com/boshek/limnotools/pull/18/files#diff-6> (5)
   - *M* man/r2b.Rd
   <https://github.com/boshek/limnotools/pull/18/files#diff-7> (5)
   - *M* man/split_interval.Rd
   <https://github.com/boshek/limnotools/pull/18/files#diff-8> (1)
   - *M* tests/testthat/test_by_s_m.R
   <https://github.com/boshek/limnotools/pull/18/files#diff-9> (73)
   - *M* tests/testthat/test_r2b.R
   <https://github.com/boshek/limnotools/pull/18/files#diff-10> (55)
   - *M* tests/testthat/test_s_m_p.R
   <https://github.com/boshek/limnotools/pull/18/files#diff-11> (52)
   - *A* tests/testthat/test_segmented.R
   <https://github.com/boshek/limnotools/pull/18/files#diff-12> (52)

Patch Links:

   - https://github.com/boshek/limnotools/pull/18.patch
   - https://github.com/boshek/limnotools/pull/18.diff

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/boshek/limnotools/pull/18>, or mute the thread

**Pull request closed without merging**
